# Generated by Django 2.2.2 on 2019-06-13 01:40

from django.db import migrations

def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()


class Migration(migrations.Migration):
    """ Django looks for this subclass of django.db.migrations.Migration when
        it loads a migration file.
        It inspect this object for four attributes, only two of which are used
        of the time. """

    #  a list of migrations this one depends on
    dependencies = [
        ('main', '0003_productimage_thumbnail'),
    ]

    # a list of Operation classes that define what this migration does
    operations = [
        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop
        ),
    ]
