# Generated by Django 2.2.2 on 2019-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basket_basketline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketline',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
